version: "3.6"

services:
  jekyll:
    image: jekyll/jekyll:3.8
    command: jekyll serve --watch --force_polling --verbose --future --unpublished
    ports:
      - 4000:4000
    volumes:
      - .:/srv/jekyll
